name: solana-alpha-agent
region: fra
services:
  - name: api
    github:
      repo: 0xksure/solana-alpha-agent
      branch: master
      deploy_on_push: true
    build_command: npm ci --omit=dev
    run_command: node dist/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3000
    envs:
      - key: RPC_URL
        value: "https://api.devnet.solana.com"
      - key: NARRATIVE_RADAR_URL
        value: "https://solana-narrative-radar-8vsib.ondigitalocean.app"
      - key: NODE_ENV
        value: "production"
